/**
 * Weapon definitions. `node` is the name of the weapon mesh that already lives in
 * the survivor character's left hand inside the glTF — we just toggle visibility.
 * `model` is the standalone glTF used for the chest pickup display.
 */
export const WEAPONS = {
  guitar: {
    key: 'guitar',
    name: 'GUITAR',
    slot: 1,
    type: 'melee',
    node: 'Guitar',
    model: 'Guitar',
    damage: 48,
    range: 2.4,
    arc: Math.PI * 0.65,
    cooldown: 0.95,
    anim: 'Slash',
    hitTime: 0.38,
    knockback: 2.5,
  },
  knife: {
    key: 'knife',
    name: 'KNIFE',
    slot: 2,
    type: 'melee',
    node: 'Knife',
    model: 'Knife',
    damage: 30,
    range: 1.8,
    arc: Math.PI * 0.45,
    cooldown: 0.4,
    anim: 'Stab',
    hitTime: 0.16,
    knockback: 0.8,
  },
  shotgun: {
    key: 'shotgun',
    name: 'SHOTGUN',
    slot: 3,
    type: 'gun',
    node: 'Shotgun',
    model: 'Shotgun',
    damage: 18,
    pellets: 7,
    spread: 0.11,
    range: 15,
    cooldown: 0.95,
    mag: 6,
    startReserve: 18,
    pickupAmmo: 12,
    reloadTime: 1.7,
    auto: false,
    recoil: 0.06,
  },
  rifle: {
    key: 'rifle',
    name: 'RIFLE',
    slot: 4,
    type: 'gun',
    node: 'Rifle',
    model: 'Rifle',
    damage: 70,
    pellets: 1,
    spread: 0.004,
    range: 70,
    cooldown: 0.65,
    mag: 8,
    startReserve: 24,
    pickupAmmo: 16,
    reloadTime: 1.9,
    auto: false,
    recoil: 0.05,
  },
  smg: {
    key: 'smg',
    name: 'SMG',
    slot: 5,
    type: 'gun',
    node: 'SMG',
    model: 'SMG',
    damage: 15,
    pellets: 1,
    spread: 0.04,
    range: 32,
    cooldown: 0.085,
    mag: 30,
    startReserve: 90,
    pickupAmmo: 60,
    reloadTime: 1.5,
    auto: true,
    recoil: 0.012,
  },
};

export const WEAPON_ORDER = ['guitar', 'knife', 'shotgun', 'rifle', 'smg'];
export const CHEST_WEAPONS = ['knife', 'shotgun', 'rifle', 'smg'];

/** Every weapon mesh name present in the survivor glTF, so we can hide the ones not in use. */
export const ALL_HAND_NODES = [
  'Axe',
  'Guitar',
  'Knife',
  'Pistol',
  'Rifle',
  'Shotgun',
  'SMG',
  'Spear',
  'WoodenBat_Barbed',
  'WoodenBat_Saw',
];
